# Generated by Django 4.2.29 on 2026-04-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_date_sale_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
